[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
hook_add = 'source ~/.config/nvim/coc-options.vim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'iberianpig/tig-explorer.vim'

[[plugins]]
repo = 'rbgrouleff/bclose.vim'

[[plugins]]
repo = "MaxMEllon/vim-jsx-pretty"
on_ft = ['javascript']

[[plugins]]
repo = "othree/yajs.vim"

[[plugins]]
repo = "mattn/emmet-vim"

[[plugins]]
repo = "tpope/vim-surround"

[[plugins]]
repo = "tpope/vim-repeat"

[[plugins]]
repo = "noahfrederick/vim-laravel"

[[plugins]]
repo = "jwalton512/vim-blade"

[[plugins]]
repo = "ryanoasis/vim-devicons"

[[plugins]]
repo     = 'prettier/vim-prettier'
build    = 'npm install'
on_ft    = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown']
hook_source = '''
  " @formatアノテーションを持ったファイルの自動フォーマットを無効にする
  let g:prettier#autoformat = 0

  " Prettierのパースエラーをquickfixに表示しない
  let g:prettier#quickfix_enabled = 0

  autocmd BufWritePre *.js,*.ts,*.vue,*.css,*.scss,*.json,*.md PrettierAsync
'''

[[plugins]]
repo = "cespare/vim-toml"
